Hooks and installing client-ts codegen on xata init
xataio/cli pull request #51
Opened 2022-03-29 15:28 UTC by gimenete

Close https://github.com/xataio/cli/issues/46
Close https://github.com/xataio/cli/issues/47

Hooks are executable files in the `xata/hooks` directory. For a given hook name the CLI will execute all executable files that start with the hook name in that directory in alphabetical order.

Users can run `xata build` to manually trigger the `build` hooks.

This PR also asks the user if they want to install the SDK and codegen on `xata init`, in which case it installs the npm packages and configures a build hook to invoke codegen.

2022-04-04 08:05 UTC, exekias commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
This won't work on windows, right? not very familiar with developing node there, I wonder if there is any way to make this compatible cross os

2022-04-04 08:09 UTC, gimenete commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
Good question. Maybe @fabien0102 can leave his opinion about that since he's a Windows user. I guess nowadays is possible and easy to run bash scripts on windows, but at the same time maybe it's not the most common thing to do? I don't know. The main thing is that we should not generate different files depending on the platform you are at the moment of generating the hook, because you are going to track the hook on git and other teammates may use other platforms. So we either:

- Generate a file that is cross-platform. Is that possible?
- Generate files with different extensions and the CLI selects which one to run in each platform depending on that.

2022-04-07 13:09 UTC, fabien0102 commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
I will try to see if this is working, but we may need a PowerShell option

2022-04-07 14:03 UTC, gimenete commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
Even of we just call "npm run something" we need to put that in a script file because I think we want hooks to be flexible and not depend necessarily on npm. The main thing to figure out is what we need to do to make that file cross platform: what extension and/or shebang and/or file permissions to use.

2022-04-07 14:04 UTC, gimenete commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
We can also generate two scripts, one for win and one for linux/mac, but I'd like to try to avoid that.

2022-04-07 14:07 UTC, exekias commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
> If someone wants to do a scripted hook that's totally fine, they can create the hook sh file and reference it from the hooks config.

yeah, that's what I meant by this, it could be like:

xata/config.json
```
{
  "schemaFileFormat": "yaml",
  "dbName": "foo",
  "workspaceID": "carlos-s-59spfr"
  "hooks": {
    "build": "npm ...",
    "pull": "./myscript.sh"
  },
}
```

myscript.sh
```
#!/bin/sh

echo "Hello world!"
```

2022-04-07 14:10 UTC, gimenete commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
Oh I see! That's a good idea 👍 I'll do that 🚀

2022-04-18 12:08 UTC, gimenete commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
Finally I had some time to update this PR.

Now I'm storing and reading hook commands from the config file. In any case I still need to get a shell to execute the command. Why?

If the user has "build: "npm a b c", then "npm" is the command and the rest are the arguments. For running this with go you'd do: `exec.Command("npm", "a", "b", "c")` or `exec.Command("npm", "a b c")` but we cannot do `exec.Command("npm a b c")` because that'd try to invoke a command named "npm a b c" that doesn't exist. We could do the parsing to split the command and the arguments, but that's tricky. For example a user may have: "build": "FOO=bar npm a b c". Then the command is still "npm" and "FOO=bar" is something only the shell understands.

By using a shell, we can just send the whole command string and the shell will interpret it. I think it's safe to assume the "SHELL" variable will always be available on Unix, and all unix shells accept the "-c" argument to run inline commands. If SHELL is not defined I think is probably safe we are on windows and we can try to use powershell in that case. I've tried the powershell thing myself since it is cross-platform (brew install powershell).

2022-04-19 15:18 UTC, amvieites commented on cmd/codegen.go
> +	if err != nil {
I'd use the initialisation statement within the `if` whenever possible, i.e. if err = _exp_; err != nil { ... }

2022-04-19 15:23 UTC, amvieites commented on cmd/hooks.go
> +	}
Maybe we could keep it simple by inverting the condition and returning right away.

2022-04-19 15:25 UTC, amvieites commented on cmd/hooks.go
> +			return err
Not sure if necessary, but maybe we should wrap this error with some context.

2022-04-19 19:54 UTC, gimenete commented on cmd/codegen.go
> +	if err != nil {
Right. I forgot about that syntax!

2022-04-19 19:54 UTC, gimenete commented on cmd/hooks.go
> +	}
Sounds good 👍

2022-04-19 19:55 UTC, gimenete commented on cmd/hooks.go
> +			return err
Yeah, every time I bubble up an error I wonder if I should wrap it or not. Do you have a rule or thumb or similar?

2022-04-20 07:01 UTC, amvieites commented on cmd/hooks.go
> +			return err
I don't have a rule of thumb in mind, in most cases I just wonder what would help me when seeing this error in a log trace. If I need to think of something right know I would say something like: _wrap an error at the highest level of the call stack that a piece of data useful for the error context is available_.

In this case `err` can be pretty much anything and maybe it makes sense to provide more context like "running command [command]:", since once we return we lose that piece of data. `settings`, `hook` or the `dir` could also make sense, I'm not sure about whole context here.

2022-04-20 09:08 UTC, exekias commented on cmd/codegen.go
> +	err = os.WriteFile(path.Join(dir, "hooks", "build"), []byte("#!/bin/bash\n./node_modules/.bin/xata-codegen generate -o client.ts"), 0744)
🎉 the approach looks good to me! I left a minor comment on the function

2022-04-20 09:31 UTC, exekias commented on cmd/hooks.go
> +	}
that means that if we find an empty `$SHELL` while running on linux/mac we will try to run `pwsh` right away 🤔 . I would rather do this to ensure we land on something that works, and propertly error out otherwise:

1. If on windows, just use `pwsh`
2. Get `$SHELL` and use it if defined (most cases will fall here)
3. If `$SHELL` is undefined, default to `/bin/sh`

In all cases, make sure we detect the error if the shell binary doesn't exist, so we can report it back to the user

2022-04-20 09:49 UTC, gimenete commented on cmd/hooks.go
> +	}
> If on windows, just use pwsh

What if you are on windows but you are using bash or zsh? That should be pretty common these days. I think we should check $SHELL first of all.

2022-04-20 09:56 UTC, exekias commented on cmd/hooks.go
> +	}
I see that point. Going for `$SHELL` first sounds good to cover for that. I believe this is not a standard env var in Windows, right? It basically means we should document this well.

In all cases, we should still fall back to something that makes sense for the current OS, and error out if the shell doesn't exist (no matter if it was given by `$SHELL` or using the default).

2022-04-20 10:02 UTC, gimenete commented on cmd/hooks.go
> +	}
👍 ok, I'll check the OS if SHELL is not defined, then will default to powershell or bash.

2022-04-20 10:48 UTC, gimenete commented on cmd/hooks.go
> +	}
PR updated!

2022-04-20 10:57 UTC, gimenete commented on cmd/hooks.go
> +			return err
Done. I've added a custom error message in this case. Thanks!

2022-04-20 10:59 UTC, gimenete commented on cmd/codegen.go
> +	settings.Hooks["build"] = "./node_modules/.bin/xata-codegen generate -o client.ts"
```suggestion
	settings.Hooks["build"] = "./node_modules/.bin/xata-codegen -o client.ts"
```

We'll change this today probably https://github.com/xataio/client-ts/pull/111

2022-04-22 10:09 UTC, exekias requested changes
This is looking great! I made a few comments but overall LGTM

2022-04-22 10:09 UTC, exekias commented on cmd/codegen.go
> +	}
at some point maybe we should ask this only if a flag is provided or we detect npm in place maybe? This is probably fine for now

2022-04-22 10:09 UTC, exekias commented on cmd/codegen.go
> +	settings.Hooks["build"] = "./node_modules/.bin/xata-codegen -o client.ts"
Hooks map may not be initialized. I think we should ensure there is always a map here in `ReadSettings`, to avoid nil map access errors

2022-04-22 10:09 UTC, exekias commented on cmd/init_e2e_test.go
> +	fmt.Println("workspaceID:", workspaceID)
leftover? If you want to have it for debugging purposes we can keep this, but use `t.Log` https://pkg.go.dev/testing#B.Log

2022-04-22 10:09 UTC, exekias commented on cmd/init_e2e_test.go
> +	_, err = c.SendLine("n")
should we have a test where we answer `y`?

2022-04-22 11:01 UTC, gimenete commented on cmd/init_e2e_test.go
> +	fmt.Println("workspaceID:", workspaceID)
Good to know that `t.Log` exists!
In this case it is a leftover so I'll remove it.

2022-04-22 11:52 UTC, gimenete commented on cmd/codegen.go
> +	settings.Hooks["build"] = "./node_modules/.bin/xata-codegen -o client.ts"
Right. Thanks! I pushed a commit to change that.

2022-04-22 11:52 UTC, gimenete commented on cmd/init_e2e_test.go
> +	_, err = c.SendLine("n")
I've added a test for that 👍

2022-04-22 11:53 UTC, gimenete commented on cmd/codegen.go
> +	}
Yeah, I was not sure about that. I think for now it's fine because most of our users will be JavaScript/TypeScript developers.

2022-04-22 13:46 UTC, exekias commented
Just had this session while testing the changes:

```
exekias-mbp.localdomain :: dev/xata/coolapp ‹init-pull*› » ../cli/cli init -f                                                    130 ↵
? Select the workspace for the database:  carlos-s-59spfr
? Do you want to pull from an existing database? coolapp
Pulling database schema...
Pulling schema from branch [coolapp:init-pull]
Pulled schema written to xata/schema.json
? Do you want to install the TypeScript SDK and code generator? Yes

up to date, audited 207 packages in 3s

35 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

up to date, audited 207 packages in 3s

35 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
zsh:1: no such file or directory: ./node_modules/.bin/xata-codegen
Error running build hook. Tried to run the following command './node_modules/.bin/xata-codegen xata -o src/xata.ts': exit status 127.
```

I guess this happened because my repo doesn't use npm? thoughts on what should we do about it?

2022-04-23 21:33 UTC, gimenete commented
@exekias that should be fixed with the latest changes! Thanks for testing. I don't understand why it didn't create a `node_modules` for you, but as we chat on Slack, running the binary with `npx` will fix that and makes the command simpler.

2022-04-25 07:58 UTC, exekias approved these changes
🎉 great feature!

2022-04-25 08:58 UTC, merged